# 使用官方的 Node.js 映像作為基礎映像
FROM node:16-alpine

# 設定工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json 到工作目錄
COPY package*.json ./

# 安裝項目依賴
RUN npm install

# 複製 Next.js 應用程式的所有文件到工作目錄
COPY . .

# 構建 Next.js 應用程式
RUN npm run build

# 暴露應用程式使用的端口（這裡假設是3000）
EXPOSE 3000

# 定義應用程式啟動命令
CMD ["npm", "start"]


# # 構建 Docker 映像
# docker build -t nextjs-app .

# # 啟動 Docker 容器
# docker run -p 3000:3000 nextjs-app
